# This rule is not used by the project node-file-injector itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to files.barpilot.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-file-injector
    app.kubernetes.io/managed-by: kustomize
  name: nodefileinjector-viewer-role
rules:
- apiGroups:
  - files.barpilot.io
  resources:
  - nodefileinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - files.barpilot.io
  resources:
  - nodefileinjectors/status
  verbs:
  - get
