---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - files.barpilot.io
  resources:
  - nodefileinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - files.barpilot.io
  resources:
  - nodefileinjectors/finalizers
  verbs:
  - update
- apiGroups:
  - files.barpilot.io
  resources:
  - nodefileinjectors/status
  verbs:
  - get
  - patch
  - update
